### ISSUE TITLE
Version 0.10.0 is not in Maven Central

### ISSUE THREAD

**Issue by matosf** [zalando-stups/spring-boot-zalando-stups-tokens#11]
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22spring-boot-zalando-stups-tokens%22

**Comment by matosf** [comment]
I saw that the artifactId changed to tokens-spring-boot-starter, and that one is there.

Maybe we should consider changing the repo name also?

**Comment by jbellmann** [comment]
Hi Fabio,
version 0.10.0 is the renamed version of 0.9.11. Maybe then we should also move it to 'zalando'-organisation? Because you can use it without 'STUPS'. Same as 'tokens' itself?
What do you think?

**Comment by matosf** [comment]
I think its a very good idea. :)

The groupId should also be updated then.
