### ISSUE TITLE
add zalando tokens as dependency

### ISSUE THREAD

**Issue by Eloberus** [zalando-stups/spring-boot-zalando-stups-tokens#12]
Either mark it as prequisite or add it as a dependency please :)

**Comment by jbellmann** [comment]
@Eloberus 
what do mean exactly? [It's a dependency in the 'sense of maven'](https://github.com/zalando-stups/spring-boot-zalando-stups-tokens/blob/master/spring-boot-zalando-stups-tokens/pom.xml#L16). Do you mean something different?

**Comment by Eloberus** [comment]
hmmm ok then i might just be wrong. I just took a look into [this pom file](https://github.com/zalando-stups/spring-boot-zalando-stups-tokens/blob/master/pom.xml) and did not find the maven dependency but that it's just my fault. Sorry for opening an issue :)

I just followed the guide in the readme and it didnt resolve the dependency for tokens.
