### ISSUE TITLE
Issue with version 0.11.0-beta-3

### ISSUE THREAD

**Issue by elgris** [zalando-stups/spring-boot-zalando-stups-tokens#19]
## How to reproduce

1. Deploy Spring application to Zalando Platform without `token` credentials.
2. Observe error
```
ERROR 11 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'secrets' defined in class path resource [org/zalando/stups/tokens/config/SecretsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.zalando.stups.tokens.Secrets]: Factory method 'secrets' threw exception; nested exception is java.lang.ClassCastException: org.zalando.stups.tokens.AccessTokenRefresher cannot be cast to org.zalando.stups.tokens.Secrets
```

## Explanation

The problem comes from dependency `tokens-0.11.0-beta-2`. It starts here: `org/zalando/stups/tokens/AccessTokensBean.java:171` when accessTokensDelegate is created

```java
accessTokensDelegate = builder.start();
```

The builder returns implementation of `org.zalando.stups.tokens.AccessTokens` interface which is fine. Internally it looks for a file with `-token-secret` suffix (check `org.zalando.stups.tokens.AccessTokensBuilder#isFilesystemSecretsLayout`) and if such file was not found, it creates an instance of `org.zalando.stups.tokens.AccessTokenRefresher`. If the file was found, it creates instance of `org.zalando.stups.tokens.fs.FilesystemSecretRefresher`.

The problem happens when `org.zalando.stups.tokens.config.SecretsAutoConfiguration` creates a bean with either `AccessTokenRefresher` or `FilesystemSecretRefresher`. It happens because  `AccessTokenRefresher` **DOES NOT** implement `Secrets` interface, so the type cast fails in method

```
    @Bean
    public Secrets secrets(AccessTokensBean accessTokensBean) {
        return new SecretsAdapter((Secrets) accessTokensBean.getDelegate());
    }
```

## Possible solution

Here are possible solutions we should discuss:

1. Make `org.zalando.stups.tokens.AccessTokenRefresher` implement `Secrets` interface
2. If a file with `-token-secret` suffix is mandatory, then throw an exception with meaningful message in case if it's not found.

**Comment by jbellmann** [comment]
Hi, thanks for reporting. I'm using this version myself and did not struggle with this issue.
But I will have a look into this over the next few days and try to reproduce it.
