### ISSUE TITLE
Update README to match latest releases.

### ISSUE THREAD

**Issue by jbellmann** [zalando-stups/spring-boot-zalando-stups-tokens#28]

**Comment by BGehrels** [comment]
*upvote*

Given that, as far as i understood, the library now shows a completely different behaviour (Reading tokens from /meta/credentials) when no config is given at all, this should be clearly documented.

**Comment by jbellmann** [comment]
@BGehrels please have a look to latest README.md. If you still think there is something missing or should be changed propose your changes in a PR please.
